openapi: 3.0.3
info:
  title: OrderService API
  version: 1.0.0
  description: Сервис заказов управляет заказами на постройку космических кораблей
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

tags:
  - name: Order
    description: Операции с данными о заказа - создание, получение и отмена заказа

paths:
  /api/v1/orders:
    $ref: ./paths/orders.yaml
  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml
  /api/v1/orders/{order_uuid}:
    $ref: ./paths/order_by_uuid.yaml
  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml
