name: CI

on:
  push:
  pull_request:

jobs:
  extract-vars:
    name: Extract Variables from Taskfile
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.extract.outputs.GO_VERSION }}
      modules: ${{ steps.extract.outputs.MODULES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Extract variables from Taskfile
        id: extract
        run: |
          chmod +x .github/scripts/extract-versions.sh
          .github/scripts/extract-versions.sh

  coverage:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test-coverage-reusable.yml
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}
      gist-id: "4a62244c443cebb5d8b94cfa746fc7f3"
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
